name: CI/CD Pipeline for IGO Marketplace Login

on:
  pull_request:
    types: [closed]
    branches: [main]  # Auto-deploy to DEV when PR is merged into main

  workflow_dispatch:  # Manual trigger for PROD deployment
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - dev
          - production

jobs:
  deploy-to-dev:
    name: Deploy to DEV (`dlviigoapps1`)
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    environment: dev
    steps:
      - name: Deploy to DEV (`dlviigoapps1`)
        run: |
          echo "🚀 Deploying to DEV on dlviigoapps1..."

          cd /srv/prep/deployments/igo-marketplace-login
          git pull

          cd igo-marketplace-login/
          npm ci
          npm run build

          cp -rT build/ ../igo-marketplace-login-backend/public/

          cd ..
          cp -rT igo-marketplace-login-backend/ /srv/www/igo-marketplace-login/
          chmod -R 775 /srv/www/igo-marketplace-login/public/

          # Restart PM2
          if pm2 list | grep -q "login"; then
            pm2 restart login
          else
            cd /srv/www/igo-marketplace-login/
            pm2 start bin/www --name login
          fi

          sleep 5
          if ! pm2 show login | grep -q "status.*online"; then
            echo "❌ Failed to start login in DEV!"
            pm2 logs login --lines 50
            exit 1
          fi

      - name: Restart NGINX on DEV
        run: |
          echo "🔄 Restarting NGINX on dlviigoapps1..."
          dzdo nginx -t && dzdo systemctl restart nginx
          echo "✅ NGINX Restarted Successfully"

  deploy-to-production:
    name: Deploy to PROD (`plviigoweb1`)
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    environment: production
    needs: deploy-to-dev
    steps:
      - name: Deploy to PROD (`plviigoweb1`)
        run: |
          echo "🚀 Deploying to PROD on plviigoweb1..."

          cd /prep/deployments/igo-marketplace-login
          git pull

          cd igo-marketplace-login/
          npm ci
          npm run build

          cp -rT build/ ../igo-marketplace-login-backend/public/

          cd ..
          cp -rT igo-marketplace-login-backend/ /srv/www/igo-marketplace-login/
          chmod -R 775 /srv/www/igo-marketplace-login/public/

          # Restart PM2
          if pm2 list | grep -q "login"; then
            pm2 restart login
          else
            cd /srv/www/igo-marketplace-login/
            pm2 start bin/www --name login
          fi

          sleep 5
          if ! pm2 show login | grep -q "status.*online"; then
            echo "❌ Failed to start login in PROD!"
            pm2 logs login --lines 50
            exit 1
          fi

      - name: Restart NGINX on PROD
        run: |
          echo "🔄 Restarting NGINX on plviigoweb1..."
          dzdo nginx -t && dzdo systemctl restart nginx
          echo "✅ NGINX Restarted Successfully"
